@baseUrl = http://localhost:9999
@ID =
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0cmFuc2FjdGlvbi1jb250cm9sIiwic3ViIjoiMGMyYWQ2MjQtOGNkOC00ZGI3LTg5ZjYtYzU4MmNkMjljNWY2Iiwicm9sZXMiOlsiQ0xJRU5UIl0sImV4cCI6MTc4MTU1MTY0OH0.adUpp4ClEOnpPiMyVR71c-CqbWzQYzlZM8_jQ_nOV1Y
### Criar um novo cliente
POST {{baseUrl}}/clientes/ 
Content-Type: application/json

{
  "username": "testuser0",
  "password": "secret",
  "confirmPassword": "secret",
  "limite": 10000,
  "saldo": 0
} 

### Autenticar o cliente (Login)
POST {{baseUrl}}/clientes/auth
Content-Type: application/json

{
  "username": "testuser0",
  "password": "secret"
}


### Trocar senha do cliente
PATCH {{baseUrl}}/clientes/password
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "new_password": "testeee",
  "confirm_new_password": "testeee"
}

### Deletar o cliente
DELETE  {{baseUrl}}/clientes/
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Adicionar nova transacao
POST  {{baseUrl}}/clientes/{{ID}}/transacoes
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "valor": 10,
    "tipo" : "d",
    "descricao" : "descricao"
}

### Consultar transacão de usuário
GET  {{baseUrl}}/clientes/{{ID}}/extrato
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
