@baseUrl = http://localhost:9999
@ID = 
@TOKEN = 
### Criar um novo cliente
POST {{baseUrl}}/clientes/ 
Content-Type: application/json

{
  "username": "testuser0",
  "password": "secret",
  "confirmPassword": "secret",
  "limite": 10000,
  "saldo": 0
} 

### Autenticar o cliente (Login)
POST {{baseUrl}}/clientes/auth
Content-Type: application/json

{
  "username": "testuser0",
  "password": "secret"
}


### Trocar senha do cliente
PATCH {{baseUrl}}/clientes/password
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "new_password": "testeee",
  "confirm_new_password": "testeee"
}

### Deletar o cliente
DELETE  {{baseUrl}}/clientes/
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Adicionar nova transacao
POST  {{baseUrl}}/clientes/{{ID}}/transacoes
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "valor": 10,
    "tipo" : "c",
    "descricao" : "descricao"
}

### Consultar transacão de usuário
GET  {{baseUrl}}/clientes/{{ID}}/extrato
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
