spring.application.name=controle-transaction
spring.datasource.url=jdbc:postgresql://localhost:5432/controle_concorrencia
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.deserialization.accept-float-as-int=false

management.endpoints.access.default=READ_ONLY
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.access=READ_ONLY
management.endpoint.health.show-details=always
management.endpoint.metrics.access=unrestricted
management.endpoint.prometheus.access=READ_ONLY

security.token.secret.client="CONCORRENCIA_TRANSACTION@123#"